2024-11-27 21:15:15,738 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:15:17,100 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:15:19,246 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:15:28,993 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:15:54,663 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:85]
2024-11-27 21:15:54,663 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:16:48,538 ERROR: Ω‚√‹ ß∞‹: Object type <class 'str'> cannot be passed to C code [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:19:23,932 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:19:30,882 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:19:43,027 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:19:45,341 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:21:39,797 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 21:21:39,798 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:22:10,791 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:22:20,433 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:22:27,180 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:22:30,364 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:23:02,653 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:23:07,716 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:23:19,866 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:84]
2024-11-27 21:23:19,866 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:23:54,497 ERROR: Ω‚√‹ ß∞‹: Object type <class 'str'> cannot be passed to C code [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:25:07,013 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:25:15,685 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:25:19,405 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:25:21,212 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:25:40,903 ERROR: Ω‚√‹ ß∞‹: Object type <class 'str'> cannot be passed to C code [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:27:38,611 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:27:42,378 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:27:46,633 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:28:05,779 ERROR: RSAΩ‚√‹¥ÌŒÛ: fromhex() argument must be str, not bytes [in d:\Code\project\Auth\app\utils.py:106]
2024-11-27 21:28:05,779 ERROR: Ω‚√‹ ß∞‹: fromhex() argument must be str, not bytes [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:28:22,574 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:28:25,530 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:28:28,285 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:28:48,316 ERROR: RSAΩ‚√‹¥ÌŒÛ: fromhex() argument must be str, not bytes [in d:\Code\project\Auth\app\utils.py:107]
2024-11-27 21:28:48,317 ERROR: Ω‚√‹ ß∞‹: fromhex() argument must be str, not bytes [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:31:33,846 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:31:53,902 ERROR: RSAΩ‚√‹¥ÌŒÛ: name 'data3' is not defined [in d:\Code\project\Auth\app\utils.py:107]
2024-11-27 21:31:53,903 ERROR: Ω‚√‹ ß∞‹: name 'data3' is not defined [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:32:17,964 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:32:50,375 ERROR: Ω‚√‹ ß∞‹: Object type <class 'str'> cannot be passed to C code [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:33:33,444 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:35:03,649 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:35:28,501 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:35:29,326 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:35:42,835 ERROR: Ω‚√‹ ß∞‹: Object type <class 'str'> cannot be passed to C code [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:36:09,391 ERROR: Ω‚√‹ ß∞‹: Object type <class 'str'> cannot be passed to C code [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:36:37,298 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:36:44,226 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:36:45,113 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:36:47,272 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:37:10,824 ERROR: AESΩ‚√‹¥ÌŒÛ: Padding is incorrect. [in d:\Code\project\Auth\app\utils.py:87]
2024-11-27 21:37:10,824 ERROR: Ω‚√‹ ß∞‹: Padding is incorrect. [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:47:12,290 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:47:33,902 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:47:35,891 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:48:02,805 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:48:13,435 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:48:23,403 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:48:40,703 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:48:53,276 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:48:54,485 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:54:13,637 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\utils.py:87]
2024-11-27 21:54:13,637 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:58:15,841 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:58:17,671 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:58:36,780 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:87]
2024-11-27 21:58:36,781 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 22:00:25,899 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:87]
2024-11-27 22:00:25,899 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 22:01:09,479 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:87]
2024-11-27 22:01:09,479 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 22:02:08,248 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 22:02:14,066 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 22:02:31,949 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:89]
2024-11-27 22:02:31,950 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 22:04:33,525 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:89]
2024-11-27 22:04:33,525 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 22:04:51,832 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 22:04:54,766 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 22:04:57,334 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 22:05:18,555 ERROR: Ω‚√‹ ß∞‹: Object type <class 'str'> cannot be passed to C code [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 22:06:16,339 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 22:06:18,245 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 22:06:22,378 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 22:06:28,984 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 22:06:31,683 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
